name: Issues Generation

concurrency: issues-generation

on:
  issue_comment:
    types: [created, deleted]
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  issue-generation-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Issue Generation
        uses: ./.github/workflows/actions/issues-generation
        id: issues-generation
        with:
          github-token: ${{ secrets.LEARNING_GITHUB_TOKEN }}
          bot-username: buildpack-bot
