name: Issues Generation

on:
  issue_comment:
    types: [created, deleted]
  pull_request_review_comment:
    types: [created, deleted]

jobs:
  issue-generation-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue Generation
        uses: ./.github/workflows/actions/issues-generation
        id: issues-generation
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
